#!/usr/bin/env python3
"""
Create Merge Request and Notify GitHub Issue

This script:
1. Creates a new branch with catalog changes
2. Creates a merge request in GitLab
3. Posts a comment to the GitHub issue with the MR link
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Optional
import requests


def run_command(cmd: list, check=True) -> subprocess.CompletedProcess:
    """Run a shell command and return result."""
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, check=check)
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        print(result.stderr, file=sys.stderr)
    return result


def create_branch_and_commit(issue_number: str, catalog_type: str) -> Optional[str]:
    """Create a new branch and commit catalog changes."""
    branch_name = f"forge/catalog-{catalog_type}-issue-{issue_number}"
    
    # Configure git
    run_command(["git", "config", "user.name", "gitlab-ci"])
    run_command(["git", "config", "user.email", f"gitlab-ci@{os.environ.get('CI_PROJECT_NAMESPACE', 'gitlab')}.gitlab.com"])
    
    # Check if there are changes to commit
    status = run_command(["git", "status", "--porcelain", "catalog/main.yaml"], check=False)
    if not status.stdout.strip():
        print("ℹ️  No changes to catalog/main.yaml")
        return None
    
    # Create and checkout new branch
    run_command(["git", "checkout", "-b", branch_name])
    
    # Add and commit changes
    run_command(["git", "add", "catalog/main.yaml"])
    commit_msg = f"Add catalog from forge (issue #{issue_number})\n\nCatalog type: {catalog_type}\nGenerated by: GitLab CI"
    run_command(["git", "commit", "-m", commit_msg])
    
    # Push branch to origin
    git_push_token = os.environ.get("CI_PUSH_TOKEN")
    ci_server_host = os.environ.get("CI_SERVER_HOST", "gitlab.com")
    ci_project_path = os.environ.get("CI_PROJECT_PATH")
    
    if not git_push_token:
        print("❌ Error: CI_PUSH_TOKEN not set")
        return None
    
    remote_url = f"https://oauth2:{git_push_token}@{ci_server_host}/{ci_project_path}.git"
    run_command(["git", "remote", "set-url", "origin", remote_url])
    run_command(["git", "push", "origin", branch_name])
    
    return branch_name


def create_merge_request(branch_name: str, issue_number: str, catalog_type: str) -> Optional[dict]:
    """Create a merge request in GitLab."""
    gitlab_token = os.environ.get("GITLAB_API_TOKEN") or os.environ.get("CI_PUSH_TOKEN")
    gitlab_host = os.environ.get("CI_SERVER_URL", "https://gitlab.com")
    project_id = os.environ.get("CI_PROJECT_ID")
    
    if not all([gitlab_token, project_id]):
        print("❌ Error: Missing GitLab API credentials")
        return None
    
    api_url = f"{gitlab_host}/api/v4/projects/{project_id}/merge_requests"
    
    headers = {
        "PRIVATE-TOKEN": gitlab_token,
        "Content-Type": "application/json"
    }
    
    data = {
        "source_branch": branch_name,
        "target_branch": "main",
        "title": f"Add catalog from forge (GitHub issue #{issue_number})",
        "description": f"""## Catalog Addition from Forge

**Source:** GitHub Issue #{issue_number}
**Catalog Type:** {catalog_type}
**Generated by:** GitLab CI/CD Pipeline

This merge request adds a new catalog entry generated from the forge workflow.

### Review Checklist
- [ ] Catalog YAML is valid
- [ ] Metadata is complete and accurate
- [ ] No conflicts with existing entries

Please review and merge if everything looks good!
""",
        "remove_source_branch": True,
        "squash": True,
        "labels": ["forge", "automated"]
    }
    
    response = requests.post(api_url, headers=headers, json=data)
    
    if response.status_code == 201:
        mr_data = response.json()
        print(f"✓ Merge request created: {mr_data['web_url']}")
        return mr_data
    else:
        print(f"❌ Failed to create merge request: {response.status_code}")
        print(response.text)
        return None


def notify_github_issue(issue_number: str, mr_data: dict, catalog_type: str) -> bool:
    """Post a comment to the GitHub issue with MR link."""
    github_token = os.environ.get("GITHUB_TOKEN")
    github_repo = os.environ.get("GITHUB_REPOSITORY")  # format: owner/repo
    
    if not all([github_token, github_repo]):
        print("⚠️  Warning: Cannot notify GitHub issue - missing credentials")
        return False
    
    owner, repo = github_repo.split("/")
    api_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    mr_url = mr_data.get("web_url")
    mr_iid = mr_data.get("iid")
    
    comment_body = f"""✅ **Catalog generated successfully!**

A merge request has been created in GitLab for review:

**Merge Request:** [!{mr_iid} - View on GitLab]({mr_url})

**Catalog Type:** `{catalog_type}`

### Next Steps
1. Review the merge request on GitLab
2. Check the generated catalog entry
3. Merge when ready

The catalog will be added to the main catalog once the MR is merged.
"""
    
    response = requests.post(api_url, headers=headers, json={"body": comment_body})
    
    if response.status_code == 201:
        print(f"✓ GitHub issue #{issue_number} updated with MR link")
        return True
    else:
        print(f"❌ Failed to update GitHub issue: {response.status_code}")
        print(response.text)
        return False


def main():
    """Main function."""
    # Check if catalog was added
    if not Path("forge_output/added_to_main.txt").exists():
        print("ℹ️  No catalog updates to process")
        return 0
    
    # Get environment variables
    issue_number = os.environ.get("GITHUB_ISSUE_NUMBER") or os.environ.get("ISSUE_NUMBER", "unknown")
    catalog_type = os.environ.get("CATALOG_TYPE", "unknown")
    
    print(f"Creating merge request for issue #{issue_number}, catalog type: {catalog_type}")
    
    # Step 1: Create branch and commit changes
    branch_name = create_branch_and_commit(issue_number, catalog_type)
    if not branch_name:
        print("❌ Failed to create branch or no changes to commit")
        return 1
    
    # Step 2: Create merge request
    mr_data = create_merge_request(branch_name, issue_number, catalog_type)
    if not mr_data:
        print("❌ Failed to create merge request")
        return 1
    
    # Step 3: Notify GitHub issue
    notify_github_issue(issue_number, mr_data, catalog_type)
    
    # Save MR info for potential future use
    output_dir = Path("forge_output")
    output_dir.mkdir(exist_ok=True)
    with open(output_dir / "merge_request.json", "w") as f:
        json.dump(mr_data, f, indent=2)
    
    print("✓ Merge request creation complete!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
