name: 🗺️ Generate STAC Catalog
description: Request generation of a STAC catalog from Earth System Model data
title: "[Forge-STAC] "
labels: ["forge-stac"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ PUBLIC INPUT NOTICE
        
        **All information you provide in this issue has to be PUBLIC and will be visible to everyone.**
        
        This includes:
        - Source URIs and data locations
        - Collection IDs and descriptions
        - Project, source, and experiment IDs
        - Any other metadata you provide
                
        ---
        
        ## STAC Catalog Generation Request
        
        This form will trigger an automated pipeline to generate a STAC (SpatioTemporal Asset Catalog) from your data.
        
        **Input requirements:**
        - Xarray-compatible datasets (Zarr, NetCDF, etc.)
        - Proper metadata (CF conventions recommended)
  
  - type: input
    id: source-uri
    attributes:
      label: Data Source URI
      description: URL or path to the dataset(s)
      placeholder: "https://example.com/data/model-output.zarr"
    validations:
      required: true

  - type: input
    id: collection-id
    attributes:
      label: Collection ID
      description: "Collection Identifier of the form '<project_id>-<activity_id>-<institution_id>-<source_id>-<experiment_id>-<version_id>'"
      placeholder: "cmip6_highresmip_mpi-esm1-2-hr_ssp585_r1i1p1f1_v20210101"

  - type: input
    id: item-id
    attributes:
      label: Item ID
      description: "Catalog entry i.e. dataset identifier. If not provided, it will be generated from the <Data Source URI>""
      placeholder: "era5-land-hourly"

  - type: markdown
    attributes:
      value: |
        ---
        
        Once submitted, the forge pipeline will:
        1. ✅ Validate your inputs
        2. 🔄 Generate the STAC catalog/collection
        3. 📦 Package the output as a downloadable artifact
        4. 💬 Comment on this issue with download instructions
        
        The artifact will be retained for 90 days.
