name: 🚀 Generate All Catalogs
description: Request generation of both Intake v2 and STAC catalogs from your data
title: "[Forge-All] "
labels: ["forge-intake", "forge-stac"]
body:
  - type: markdown
    attributes:
      value: |
        ## Generate All Catalogs
        
        This form will trigger automated pipelines to generate both:
        - **Intake v2 Catalog** - For data access and discovery
        - **STAC Catalog** - For spatiotemporal asset cataloging
        
        **Input requirements:**
        - Xarray-compatible datasets (Zarr, NetCDF, etc.)
        - Proper metadata (CF conventions recommended)
  
  - type: input
    id: source-uri
    attributes:
      label: Data Source URI
      description: URL or path to the dataset(s)
      placeholder: "https://example.com/data/model-output.zarr"
    validations:
      required: true

  - type: input
    id: collection-id
    attributes:
      label: Collection/Catalog ID
      description: Unique identifier for the catalogs
      placeholder: "eerie-icon-ngc4008"
    validations:
      required: true

  - type: input
    id: project-id
    attributes:
      label: Project ID
      description: Project identifier (e.g., EERIE, NextGEMS, COSMO)
      placeholder: "EERIE"
    validations:
      required: true

  - type: input
    id: source-id
    attributes:
      label: Source ID (Model)
      description: Model or source identifier
      placeholder: "ICON"

  - type: input
    id: experiment-id
    attributes:
      label: Experiment ID
      description: Experiment identifier
      placeholder: "ngc4008"

  - type: textarea
    id: spatial-extent
    attributes:
      label: Spatial Extent (STAC)
      description: |
        Bounding box for the data [west, south, east, north]
        Leave empty for auto-detection
      placeholder: "[-180, -90, 180, 90]"

  - type: textarea
    id: temporal-extent
    attributes:
      label: Temporal Extent (STAC)
      description: |
        Time range for the data (ISO 8601 format)
        Leave empty for auto-detection
      placeholder: |
        start: 2020-01-01T00:00:00Z
        end: 2021-12-31T23:59:59Z

  - type: textarea
    id: description
    attributes:
      label: Collection Description
      description: Detailed description of the dataset
      placeholder: "High-resolution Earth System Model output from the EERIE project"
    validations:
      required: true

  - type: dropdown
    id: source-type
    attributes:
      label: Source Type (Intake)
      description: What type of source are you converting from?
      options:
        - Zarr Store
        - Intake v1 YAML Catalog
        - Reference Parquet
        - Auto-detect
      default: 3

  - type: textarea
    id: additional-options
    attributes:
      label: Additional Options (Intake)
      description: |
        Any additional command-line options for tointake2 (one per line).
        See the tool documentation for available options.
      placeholder: |
        --verbose
        --include-pattern '*.zarr'
      value: ""

  - type: input
    id: stac-api-url
    attributes:
      label: STAC API URL (optional)
      description: If provided, attempt to publish to this STAC API endpoint
      placeholder: "https://stac.example.com/api"

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: "Use EERIE Cloud template (STAC)"
          required: false
        - label: "Make catalogs publicly accessible"
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        Once submitted, the forge pipeline will:
        1. ✅ Validate your inputs
        2. 🔄 Generate the Intake v2 catalog
        3. 🗺️ Generate the STAC catalog
        4. 📦 Package both outputs as downloadable artifacts
        5. 💬 Comment on this issue with download instructions
        
        Both artifacts will be retained for 90 days.
