name: 🗺️ Generate STAC Catalog
description: Request generation of a STAC catalog from Earth System Model data
title: "[Forge-STAC] "
labels: ["forge-stac"]
body:
  - type: markdown
    attributes:
      value: |
        ## STAC Catalog Generation Request
        
        This form will trigger an automated pipeline to generate a STAC (SpatioTemporal Asset Catalog) from your data.
        
        **Input requirements:**
        - Xarray-compatible datasets (Zarr, NetCDF, etc.)
        - Proper metadata (CF conventions recommended)
  
  - type: input
    id: source-uri
    attributes:
      label: Data Source URI
      description: URL or path to the dataset(s)
      placeholder: "https://example.com/data/model-output.zarr"
    validations:
      required: true

  - type: input
    id: collection-id
    attributes:
      label: Collection ID
      description: Unique identifier for the STAC collection
      placeholder: "eerie-icon-ngc4008"
    validations:
      required: true

  - type: input
    id: project-id
    attributes:
      label: Project ID
      description: Project identifier (e.g., EERIE, NextGEMS, COSMO)
      placeholder: "EERIE"
    validations:
      required: true

  - type: input
    id: source-id
    attributes:
      label: Source ID (Model)
      description: Model or source identifier
      placeholder: "ICON"

  - type: input
    id: experiment-id
    attributes:
      label: Experiment ID
      description: Experiment identifier
      placeholder: "ngc4008"

  - type: textarea
    id: spatial-extent
    attributes:
      label: Spatial Extent
      description: |
        Bounding box for the data [west, south, east, north]
        Leave empty for auto-detection
      placeholder: "[-180, -90, 180, 90]"

  - type: textarea
    id: temporal-extent
    attributes:
      label: Temporal Extent
      description: |
        Time range for the data (ISO 8601 format)
        Leave empty for auto-detection
      placeholder: |
        start: 2020-01-01T00:00:00Z
        end: 2021-12-31T23:59:59Z

  - type: textarea
    id: description
    attributes:
      label: Collection Description
      description: Detailed description of the dataset
      placeholder: "High-resolution Earth System Model output from the EERIE project"
    validations:
      required: true

  - type: input
    id: stac-api-url
    attributes:
      label: STAC API URL (optional)
      description: If provided, attempt to publish to this STAC API endpoint
      placeholder: "https://stac.example.com/api"

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: "Use EERIE Cloud template"
          required: false
        - label: "Generate preview thumbnails"
          required: false
        - label: "Include Kerchunk references"
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        Once submitted, the forge pipeline will:
        1. ✅ Validate your inputs
        2. 🔄 Generate the STAC catalog/collection
        3. 📦 Package the output as a downloadable artifact
        4. 💬 Comment on this issue with download instructions
        
        The artifact will be retained for 90 days.
